/* styles.css */

body {
    font-family: Arial, sans-serif;
    line-height: 1.6;
    margin: 0;
    padding: 0;
    color: #333;
}

header {
    background: #1a1a2e;
    color: #fff;
    padding: 20px 0;
    text-align: center;
}

header h1 {
    margin: 0;
    font-size: 2.5rem;
}

header p {
    font-size: 1.2rem;
}

nav {
    background: #16213e;
    padding: 10px 0;
    text-align: center;
}

nav ul {
    list-style: none;
    padding: 0;
    margin: 0;
    display: flex;
    justify-content: center;
}

nav ul li {
    margin: 0 15px;
}

nav ul li a {
    color: #fff;
    text-decoration: none;
    font-weight: bold;
    transition: color 0.3s;
}

nav ul li a:hover {
    color: #ffa62b;
}

.section {
    padding: 20px;
    max-width: 800px;
    margin: 20px auto;
    background: #f8f8f8;
    border-radius: 8px;
    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
}

.section h2 {
    color: #16213e;
    margin-bottom: 10px;
}

.section ul {
    list-style: square;
    padding-left: 20px;
}

.section .btn {
    display: inline-block;
    background: #ffa62b;
    color: #fff;
    padding: 10px 20px;
    text-decoration: none;
    border-radius: 5px;
    transition: background 0.3s;
}

.section .btn:hover {
    background: #e68a00;
}

footer {
    text-align: center;
    background: #1a1a2e;
    color: #fff;
    padding: 10px 0;
    margin-top: 20px;
    font-size: 0.9rem;
}
